apiVersion: networking.x-k8s.io/v1alpha1
kind: HTTPRoute
metadata:
  name: route-echo-http-1
  labels:
    route: route-echo
spec:
  gateways:
    allow: SameNamespace
    gatewayRefs:
      - name: private-gateway
        namespace: default
  hostnames:
    - "localhost"
  rules:
    - matches:
        - path:
            type: Exact
            value: /echo
      forwardTo:
        - serviceName: echoservice
          port: 8080
          weight: 100
    - matches:
        - path:
            type: Exact
            value: /get
      forwardTo:
        - serviceName: httpbin.org
          port: 80
          weight: 100