apiVersion: v1
entries:
  verticle-gateway-operator:
  - apiVersion: v2
    appVersion: 0.0.1-SNAPSHOT
    created: "2021-07-02T21:44:52.772454+02:00"
    description: A Kubernetes Operator spawning Spring Cloud Gateways using CRDs
    digest: a876caed2f5be98a46fea7468560cd618027f326d7587c7df17d36e5bebd279b
    name: verticle-gateway-operator
    type: application
    urls:
    - verticle-gateway-operator-0.1.0.tgz
    version: 0.1.0
generated: "2021-07-02T21:44:52.771392+02:00"
